<?php

// 

$wearableAssets = [
    Asset::create([
        'name' => 'cap',
        'description' => 'is cap',
        'author' => 'ro blocks',
        'assetId' => 417457461,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'buny ears',
        'description' => 'is buny.',
        'author' => 'ro blocks',
        'assetId' => 1080949,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'golden hair',
        'description' => 'is hair!',
        'author' => 'ro blocks',
        'assetId' => 13476917,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'ushasnka brown',
        'description' => 'is hat!',
        'author' => 'ro blocks',
        'assetId' => 10914014,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'domo jeans',
        'description' => 'is jeans!',
        'author' => 'ro blocks',
        'assetId' => 7581780596,
        'version' => -1,
        'assetType' => AssetType::PANTS,
    ]),
    Asset::create([
        'name' => 'pants t hat should be jeans',
        'description' => 'but they point to a gear!',
        'author' => 'ro blocks',
        'assetId' => 8645397678,
        'version' => -1,
        'assetType' => AssetType::PANTS,
    ]),
    Asset::create([
        'name' => 'domo shirt',
        'description' => 'is hat!',
        'author' => 'ro blocks',
        'assetId' => 7344168483,
        'version' => -1,
        'assetType' => AssetType::SHIRT,
    ]),
    Asset::create([
        'name' => 'Official Erik Shirt',
        'description' => 'To honor our co-founder Erik Cassel, ROBLOX will make a substantial contribution to cancer research in Erik\'s name. Thank you to everyone for your respect and support.',
        'author' => 'ro blocks',
        'assetId' => 106779740,
        'version' => -1,
        'assetType' => AssetType::SHIRT,
    ]),
    Asset::create([
        'name' => 'stick battle!!!.png',
        'description' => 'This item is available in your inventory.',
        'author' => 'kirby0628',
        'assetId' => 1576264,
        'version' => -1,
        'assetType' => AssetType::TSHIRT,
    ]),
    Asset::create([
        'name' => 'Awkward....',
        'description' => 'Wow... that was awkward.',
        'author' => 'roblox',
        'assetId' => 23932048,
        'version' => -1,
        'assetType' => AssetType::FACE,
    ]),
    Asset::create([
        'name' => 'America\'s Sweetheart',
        'description' => 'Patriotic and stylish, this hair will have you looking great for the 4th of July.',
        'author' => 'roblox',
        'assetId' => 29952810,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'Bird of Prey',
        'description' => 'Tastes like chicken. Fights like raptor.',
        'author' => 'roblox',
        'assetId' => 10907547,
        'version' => -1,
        'assetType' => AssetType::FACE,
    ]),
    Asset::create([
        'name' => 'Dark Blue Light Hair',
        'description' => '"You are the bluest light, you are the bluest light!"',
        'author' => 'roblox',
        'assetId' => 76059443,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]), 
    Asset::create([
        'name' => 'Colorful Lazer',
        'description' => 'Pew pew pew!',
        'author' => 'AceSparkles',
        'assetId' => 542406569,
        'version' => -1,
        'assetType' => AssetType::SHIRT,
    ]),
    Asset::create([
        'name' => 'Vegetable Hat',
        'description' => 'Pray someone doesn\'t jump on your head and harvest your plant.',
        'author' => 'roblox',
        'assetId' => 1098273,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'Classic ROBLOX Pumpkin Head',
        'description' => 'Happy Halloween 2008-2017!',
        'author' => 'roblox',
        'assetId' => 1158038,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'Screw',
        'description' => 'Threaded fastener, Twist around; face them! Hold fast – Lest they be faster.',
        'author' => 'roblox',
        'assetId' => 1090516,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'Normal Hair',
        'description' => 'Boring? Or Classic?',
        'author' => 'roblox',
        'assetId' => 20643008,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'Purple Banded Top Hat',
        'description' => 'This dapper accouterment is a symbol of wealth and prestige. Perfect for Victorian Balls and award ceremonies.',
        'author' => 'roblox',
        'assetId' => 1028715,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'Nerd Glasses',
        'description' => 'Microsoft: "You\'ve got questions. We\'ve got dancing paperclips."',
        'author' => 'roblox',
        'assetId' => 11884330,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'Mysterious',
        'description' => '"Be extremely subtle, even to the point of formlessness. Be extremely mysterious, even to the point of soundlessness. Thereby you can be the director of the opponent\'s fate." - Sun-tzu (~400 BC), The Art of War. Emptiness and Fullness ',
        'author' => 'roblox',
        'assetId' => 7132035,
        'version' => -1,
        'assetType' => AssetType::FACE,
    ]),
];