<?php

// 

$wearableAssets = [
    Asset::create([
        'name' => 'cap',
        'description' => 'is cap',
        'author' => 'ro blocks',
        'assetId' => 417457461,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'buny ears',
        'description' => 'is buny.',
        'author' => 'ro blocks',
        'assetId' => 1080949,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'golden hair',
        'description' => 'is hair!',
        'author' => 'ro blocks',
        'assetId' => 13476917,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'ushasnka brown',
        'description' => 'is hat!',
        'author' => 'ro blocks',
        'assetId' => 10914014,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'domo jeans',
        'description' => 'is jeans!',
        'author' => 'ro blocks',
        'assetId' => 7581780596,
        'version' => -1,
        'assetType' => AssetType::PANTS,
    ]),
    Asset::create([
        'name' => 'pants t hat should be jeans',
        'description' => 'but they point to a gear!',
        'author' => 'ro blocks',
        'assetId' => 8645397678,
        'version' => -1,
        'assetType' => AssetType::PANTS,
    ]),
    Asset::create([
        'name' => 'domo shirt',
        'description' => 'is hat!',
        'author' => 'ro blocks',
        'assetId' => 7344168483,
        'version' => -1,
        'assetType' => AssetType::SHIRT,
    ]),
    Asset::create([
        'name' => 'Official Erik Shirt',
        'description' => 'To honor our co-founder Erik Cassel, ROBLOX will make a substantial contribution to cancer research in Erik\'s name. Thank you to everyone for your respect and support.',
        'author' => 'ro blocks',
        'assetId' => 106779740,
        'version' => -1,
        'assetType' => AssetType::SHIRT,
    ]),
    Asset::create([
        'name' => 'stick battle!!!.png',
        'description' => 'This item is available in your inventory.',
        'author' => 'kirby0628',
        'assetId' => 1576264,
        'version' => -1,
        'assetType' => AssetType::TSHIRT,
    ]),
    Asset::create([
        'name' => 'Awkward....',
        'description' => 'Wow... that was awkward.',
        'author' => 'roblox',
        'assetId' => 23932048,
        'version' => -1,
        'assetType' => AssetType::FACE,
    ]),
    Asset::create([
        'name' => 'America\'s Sweetheart',
        'description' => 'Patriotic and stylish, this hair will have you looking great for the 4th of July.',
        'author' => 'roblox',
        'assetId' => 29952810,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'Bird of Prey',
        'description' => 'Tastes like chicken. Fights like raptor.',
        'author' => 'roblox',
        'assetId' => 10907547,
        'version' => -1,
        'assetType' => AssetType::FACE,
    ]),
    Asset::create([
        'name' => 'Dark Blue Light Hair',
        'description' => '"You are the bluest light, you are the bluest light!"',
        'author' => 'roblox',
        'assetId' => 76059443,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]), 
    Asset::create([
        'name' => 'Colorful Lazer',
        'description' => 'Pew pew pew!',
        'author' => 'AceSparkles',
        'assetId' => 542406569,
        'version' => -1,
        'assetType' => AssetType::SHIRT,
    ]),
    Asset::create([
        'name' => 'Vegetable Hat',
        'description' => 'Pray someone doesn\'t jump on your head and harvest your plant.',
        'author' => 'roblox',
        'assetId' => 1098273,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'Classic ROBLOX Pumpkin Head',
        'description' => 'Happy Halloween 2008-2017!',
        'author' => 'roblox',
        'assetId' => 1158038,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'Screw',
        'description' => 'Threaded fastener, Twist around; face them! Hold fast – Lest they be faster.',
        'author' => 'roblox',
        'assetId' => 1090516,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'Normal Hair',
        'description' => 'Boring? Or Classic?',
        'author' => 'roblox',
        'assetId' => 20643008,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'Purple Banded Top Hat',
        'description' => 'This dapper accouterment is a symbol of wealth and prestige. Perfect for Victorian Balls and award ceremonies.',
        'author' => 'roblox',
        'assetId' => 1028715,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'Nerd Glasses',
        'description' => 'Microsoft: "You\'ve got questions. We\'ve got dancing paperclips."',
        'author' => 'roblox',
        'assetId' => 11884330,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'Mysterious',
        'description' => '"Be extremely subtle, even to the point of formlessness. Be extremely mysterious, even to the point of soundlessness. Thereby you can be the director of the opponent\'s fate." - Sun-tzu (~400 BC), The Art of War. Emptiness and Fullness ',
        'author' => 'roblox',
        'assetId' => 7132035,
        'version' => -1,
        'assetType' => AssetType::FACE,
    ]),
    Asset::create([
        'name' => 'Emerald Eye',
        'description' => 'Here\'s looking at you, kid.',
        'author' => 'roblox',
        'assetId' => 1185264,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'Empyrean Reignment',
        'description' => '"…who overcomes / By force, hath overcome but half his foe."',
        'author' => 'roblox',
        'assetId' => 15967743,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'Colorful Lazer',
        'description' => 'Pew pew pew!',
        'author' => 'AceSparkles',
        'assetId' => 542406569,
        'version' => -1,
        'assetType' => AssetType::SHIRT,
    ]),
    Asset::create([
        'name' => 'Al Capwn',
        'description' => 'He\'ll make sure you sleep with the fishes. And he isn\'t talking about going on a fishing trip...',
        'author' => 'Roblox',
        'assetId' => 24123795,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'Al Capwn',
        'description' => 'He\'ll make sure you sleep with the fishes. And he isn\'t talking about going on a fishing trip...',
        'author' => 'Roblox',
        'assetId' => 24123795,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'Auburn Scene Hair',
        'description' => 'My hair is art, dude.',
        'author' => 'roblox',
        'assetId' => 62246484,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'Comedy',
        'description' => 'LOL',
        'author' => 'roblox',
        'assetId' => 13702134,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'Tragedy',
        'description' => 'QQ',
        'author' => 'roblox',
        'assetId' => 13702160,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'Midnight Shades',
        'description' => 'I wouldn\'t actually wear them at midnight. People might get the wrong idea.',
        'author' => 'roblox',
        'assetId' => 30331986,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'Welding Mask',
        'description' => 'Ain\'t nothing more manly than a welding mask. That\'s what I think anyways...',
        'author' => 'roblox',
        'assetId' => 10832141,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'Polar Bear',
        'description' => 'How can something so ferocious be so totes adorbs?  I don\'t know either...',
        'author' => 'roblox',
        'assetId' => 41856690,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'Perfectly Legitimate Business Hat',
        'description' => 'aka Al Capwn',
        'author' => 'roblox',
        'assetId' => 19027209,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'Hip Hop Ninja',
        'description' => 'Defendin\' the dojo - one rhyme at a time!',
        'author' => 'roblox',
        'assetId' => 38323046,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'Pal Face',
        'description' => 'No description.',
        'author' => 'roblox',
        'assetId' => 86485810,
        'version' => -1,
        'assetType' => AssetType::FACE,
    ]),
    Asset::create([
        'name' => 'Dr. Smyth Face',
        'description' => 'Gotta luv dah cutie face c:',
        'author' => 'roblox',
        'assetId' => 76382978,
        'version' => -1,
        'assetType' => AssetType::FACE,
    ]),
    Asset::create([
        'name' => 'Buddy Face',
        'description' => 'No description.',
        'author' => 'roblox',
        'assetId' => 66330339,
        'version' => -1,
        'assetType' => AssetType::FACE,
    ]),
    Asset::create([
        'name' => 'Derp Face',
        'description' => 'No description.',
        'author' => 'roblox',
        'assetId' => 66330120,
        'version' => -1,
        'assetType' => AssetType::FACE,
    ]),
    Asset::create([
        'name' => 'Crimson Winter Scarf',
        'description' => 'Baby, it\'s cold outside.',
        'author' => 'roblox',
        'assetId' => 99860652,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'Heeeeeey...',
        'description' => 'Watch me jump this shark!',
        'author' => 'Roblox',
        'assetId' => 21635565,
        'version' => -1,
        'assetType' => AssetType::FACE,
    ]),
];