<?php

// 

$wearableAssets = [
    Asset::create([
        'name' => 'cap',
        'description' => 'is cap',
        'author' => 'ro blocks',
        'assetId' => 417457461,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'buny ears',
        'description' => 'is buny.',
        'author' => 'ro blocks',
        'assetId' => 1080949,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'golden hair',
        'description' => 'is hair!',
        'author' => 'ro blocks',
        'assetId' => 13476917,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'ushasnka brown',
        'description' => 'is hat!',
        'author' => 'ro blocks',
        'assetId' => 10914014,
        'version' => -1,
        'assetType' => AssetType::HAT,
    ]),
    Asset::create([
        'name' => 'domo jeans',
        'description' => 'is jeans!',
        'author' => 'ro blocks',
        'assetId' => 7581780596,
        'version' => -1,
        'assetType' => AssetType::PANTS,
    ]),
    Asset::create([
        'name' => 'pants t hat should be jeans',
        'description' => 'but they point to a gear!',
        'author' => 'ro blocks',
        'assetId' => 8645397678,
        'version' => -1,
        'assetType' => AssetType::PANTS,
    ]),
    Asset::create([
        'name' => 'domo shirt',
        'description' => 'is hat!',
        'author' => 'ro blocks',
        'assetId' => 7344168483,
        'version' => -1,
        'assetType' => AssetType::SHIRT,
    ]),
    Asset::create([
        'name' => 'Official Erik Shirt',
        'description' => 'To honor our co-founder Erik Cassel, ROBLOX will make a substantial contribution to cancer research in Erik\'s name. Thank you to everyone for your respect and support.',
        'author' => 'ro blocks',
        'assetId' => 106779740,
        'version' => -1,
        'assetType' => AssetType::SHIRT,
    ]),
    Asset::create([
        'name' => 'stick battle!!!.png',
        'description' => 'This item is available in your inventory.',
        'author' => 'kirby0628',
        'assetId' => 1576264,
        'version' => -1,
        'assetType' => AssetType::TSHIRT,
    ]),
    Asset::create([
        'name' => 'Awkward....',
        'description' => 'Wow... that was awkward.',
        'author' => 'roblox',
        'assetId' => 23932048,
        'version' => -1,
        'assetType' => AssetType::FACE,
    ]),
];